### ISSUE TITLE
[COMPILE - GRADLE] Doesn't work

### ISSUE THREAD

**Issue by DonKolia** [Wynntils/Artemis#2085]
Doesn't work the mod Fabric, Forge in client. Client coesn't loads the mod. Only loads the original in client.

**Comment by kristofbolyai** [comment]
Well.. it does work. Perhaps provide any useful info..?

**Comment by DonKolia** [comment]
![image](https://github.com/Wynntils/Artemis/assets/55564649/90b0e7fb-fa2a-4353-bb28-f469ac080958)
Dude, i try everything WTF

**Comment by DonKolia** [comment]
This is the first time that a compilation does not work for me.

**Comment by DonKolia** [comment]
i did

**Comment by DonKolia** [comment]
![image](https://github.com/Wynntils/Artemis/assets/55564649/c72e5329-e2c9-4921-8db7-06f4eff6e285)

**Comment by DonKolia** [comment]
Yes yes, i got it. Thanks!
